spring:
  datasource:
    hikari:
      username: root
      password: 150938
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoder=utf8
    driver-class-name: com.mysql.jdbc.Driver


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

server:
  port: 8080
